version: "3.8"

services: 
  multiplica-api:
    container_name: multiplica-api
    build: 
      context: .
      dockerfile: Dockerfile.multiplica-api
    image: multiplica-api:0.1
    volumes: 
      - ${API_PATH}:/app
    ports: 
      - "${API_PORT}:8080"
    logging:
      options:
        max-size: 3m
    depends_on:
      - multiplica-pg

  # multiplica-api:
  #   container_name: multiplica-api
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.multiplica-api-prod
  #   image: multiplica-api:1.0
  #   ports: 
  #     - "${API_PORT}:8080"
  #   logging:
  #     options:
  #       max-size: 3m
  #   depends_on:
  #     - multiplica-pg

  multiplica-pg:
    container_name: multiplica-pg
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - "${DB_PATH}:/var/lib/postgresql/data"

  multiplica-adminer:
    build:
      context: .
      dockerfile: Dockerfile.multiplica-adminer
    image: multiplica-adminer:0.1
    container_name: multiplica-adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080