version: "3.8"

services: 
  multiplica-api:
    container_name: multiplica-api
    build: 
      context: .
      dockerfile: Dockerfile.multiplica-api
    volumes: 
      - ${API_PATH}:/app
    ports: 
      - "${API_PORT}:8080"
    logging:
      options:
        max-size: 3m

  multiplica-pg:
    container_name: multiplica-pg
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    ports:
      - ${PG_PORT}:5432
    volumes:
      - "${PG_PATH}:/var/lib/postgresql/data"

  multiplica-adminer:
    build:
      context: .
      dockerfile: Dockerfile.multiplica-adminer
    image: multiplica-adminer:0.1
    container_name: multiplica-adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080